---
name: Run clang-format linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-clang-format:
    uses: secretflow/.github/.github/workflows/clang-format.yml@main
